## The profile with cache requires mysql, redis, zookeeper, kafka and debezium.
## You can run `<jimmer_home>/example/env-with-cache/debezium/install.sh` to install them in docker

spring:

  # Redisson has been disabled in default profile, enable it in this profile
  autoconfigure:
    exclude: # Exclude nothing

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5200/jimmer_demo
    username: root
    password: 123456
  redis:
    host: localhost
    port: 5400
  kafka:
    consumer:
      bootstrap-servers: localhost:5100
      group-id: jimmer-demo/sql-grpahql
      enable-auto-commit: false
      auto-offset-reset: latest
    listener:
      ack-mode: MANUAL_IMMEDIATE

jimmer:
  dialect: org.babyfish.jimmer.sql.dialect.PostgresDialect