spring:
  application:
    name: author-service
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:author-db;database_to_upper=true

jimmer:
  micro-service-name: ${spring.application.name}
  show-sql: true
  pretty-sql: true
  executor-context-prefixes:
    - org.babyfish.jimmer.example.cloud.author.AuthorService
  database-validation-mode: ERROR
  client:
    ts:
      path: /author-service-ts.zip
    openapi:
      path: /openapi.yml
      ui-path: /openapi.html
      properties:
        info:
          title: Openapi of store-service
          description: "`/author/{id}` accesses current service, `/author/{id}/detail` accesses all services"
          version: "0.9.10"

server:
  port: 7003

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7000/eureka/
